### ISSUE TITLE
Automate Bash Script

### ISSUE THREAD

**Issue by Teerapat6509650468** [Kwandao6509650245/CS360_Project#3]
**Description**
Create a Bash script to automate the process of cloning a repository from GitHub to an EC2 instance and running a Strapi application. This will facilitate a streamlined deployment process.

**Tasks**
- [x] Create a Bash script to clone the GitHub repository to the EC2 instance.
- [x] Install necessary dependencies for the Strapi app on the EC2 instance.
- [x] Configure and start the Strapi application on the EC2 instance.
- [x] Test the script to ensure it functions correctly.
- [x] Document how to use the script and commit it to GitHub.
