### ISSUE TITLE
Improve bash script (feedback from Sprint 1)

### ISSUE THREAD

**Issue by Kwandao6509650245** [Kwandao6509650245/CS360_Project#36]
**Description**
Improve and fix the Bash script based on feedback from Sprint 1.

**Task**
- [x] Ensure function names are consistent; currently, some are in Pascal Case while others are in Camel Case.
- [x] Remove unnecessary comments, such as "Function to check for Git installation." 
- [x] Reformat line 106 to improve readability.
- [x] Simplify line 115 by using the operator on line 118.
- [x] Review line 131; it may be unnecessary.
- [x] Adjust the deploy function to call configPM2 directly, as ecosystem.config.js is already required.
- [x] Modify line 169 to prevent a new clone each time the script is run, which currently results in nested repositories.
- [x] Move the deploy script to the root level of the project for easier access and organization.

**Comment by Kwandao6509650245** [comment]
Review line 131; it may be unnecessary.
In my opinion, I think this line is necessary. What do you guys think?
