### ISSUE TITLE
Research Strapi CMS for Integration and Feature Evaluation

### ISSUE THREAD

**Issue by Teerapat6509650468** [Kwandao6509650245/CS360_Project#4]
**Description**
Conduct a comprehensive research on Strapi CMS to understand its core features, technology stack, use cases, pros and cons, and how it compares to other CMS options. This will help us evaluate its potential for future projects.

**Tasks**

- [x]  Gather an overview of Strapi and its main features (headless CMS, customization).
- [x]  Explore Strapi’s technology stack (Node.js, database compatibility).
- [x]  Try to build and run simple Strapi app.
