### ISSUE TITLE
Dynamic IP Configuration

### ISSUE THREAD

**Issue by Kwandao6509650245** [Kwandao6509650245/CS360_Project#40]
**Description**
Instead of hard-coding the IP Address in http.js, we should retrieve it from the .env file to allow for easier configuration and greater flexibility in the code.

**Task**
- [x] Modify http.js to import the IP Address from the .env file.
- [x] Test the application functionality after making the changes.
- [x] Ensure that CORS works correctly across different environments.
