### ISSUE TITLE
CI/CD pipeline

### ISSUE THREAD

**Issue by Panapol6509650146** [Kwandao6509650245/CS360_Project#50]
**Description**
To set up and implement a CI/CD pipeline for the pet_adoption repository to ensure automated builds, testing, deployments and improving development workflow.

**Tasks**

- [x] Configure git-secret for securely managing sensitive data
- [x] Create CI pipeline
- [x] Create CD pipeline
- [x] Create user-data.sh to automated deploy in EC2
- [ ] Test pipeline execution and debug errors
