### ISSUE TITLE
Create Additional Branches for Pull Requests

### ISSUE THREAD

**Issue by Teerapat6509650468** [Kwandao6509650245/CS360_Project#7]
**Description**
Create multiple branches, such as develop and bash-script, for structured feature development and ensure Pull Requests are utilized for merging into master.

**Tasks**

- [x] Create develop, bash-script, and any other necessary feature branches.
- [x] Ensure all new features or fixes are developed on separate branches.
- [x] Create Pull Requests for merging into master.
- [x] Review code in Pull Requests before approving and merging.
